Updates to BLS precompiles (EIP-2537)
ethereum/evmone pull request #1089
Opened 2024-12-20 09:19 UTC by chfast

Apply recent [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) spec updates:
- update gas costs:
  - https://github.com/ethereum/EIPs/pull/9097
  - https://github.com/ethereum/EIPs/pull/9098
  - https://github.com/ethereum/EIPs/pull/9116
- remove redundant MUL precompiles:
  - https://github.com/ethereum/EIPs/pull/8945

2025-01-15 10:25 UTC, rodiazet requested changes
It's OK in general. A few nits to be fixed.

2025-01-15 10:25 UTC, rodiazet commented on test/state/precompiles.cpp
>      if (input.empty() || input.size() % 160 != 0)
Can we define single input size and use ut here and below? Same for G2

2025-01-15 10:25 UTC, rodiazet commented on test/state/precompiles.cpp
> +    static constexpr auto BLS12_G1ADD_PRECOMPILE_GAS = 375;
If we are not going to squash the commits before merging this change should go to different commit.

2025-01-15 10:25 UTC, rodiazet commented on test/state/precompiles.cpp
> +    static constexpr auto BLS12_G1ADD_PRECOMPILE_GAS = 375;
Same applies to g2add, g2mul, pairing, g2 map analysis

2025-01-15 10:25 UTC, rodiazet commented on test/state/precompiles.cpp
> -ExecutionResult bls12_g1mul_execute(const uint8_t* input, size_t input_size, uint8_t* output,
Remove also their `analysis` counterparts for g1 and g2. Here and from the header.

2025-01-17 16:17 UTC, chfast commented on test/state/precompiles.cpp
> +    static constexpr auto BLS12_G1ADD_PRECOMPILE_GAS = 375;
squashed.

2025-01-17 16:37 UTC, chfast commented on test/state/precompiles.cpp
>      if (input.empty() || input.size() % 160 != 0)
I defined constants for sizes, but not used it `&input[64]`... I think the input handling may need separate improvement.

2025-01-17 16:37 UTC, chfast commented on test/state/precompiles.cpp
> -ExecutionResult bls12_g1mul_execute(const uint8_t* input, size_t input_size, uint8_t* output,
Removed.

2025-01-20 10:22 UTC, rodiazet approved these changes

2025-01-20 15:56 UTC, merged