Add output operator for EOFValidationError to be used by Google.Test
ethereum/evmone pull request #639
Opened 2023-05-08 13:35 UTC by gumb0

This makes EOF validation tests output better failures.

2023-05-09 13:49 UTC, gumb0 commented
> Why not just `operator<<`?

yeah, it works too, then I'll put it into `eof.hpp`

2023-05-09 13:56 UTC, chfast commented
> > Why not just `operator<<`?
> 
> yeah, it works too, then I'll put it into `eof.hpp`

Go ahead.

2023-05-09 14:05 UTC, chfast requested changes

2023-05-10 11:44 UTC, chfast approved these changes

2023-05-10 12:49 UTC, merged