Implement EIP-4788: Beacon block root in the EVM
ethereum/evmone pull request #709
Opened 2023-09-24 14:32 UTC by chfast

2023-11-24 12:21 UTC, rodiazet commented on test/state/state.cpp
> +void system_call(State& state, const BlockInfo& block, evmc_revision rev, evmc::VM& vm)
Can we easily add unit tests for this function?

2023-11-24 17:43 UTC, gumb0 approved these changes

2023-11-24 17:45 UTC, gumb0 requested changes
Unit test fails on sanitizer build

2023-11-24 18:17 UTC, chfast commented
> Looks good, but unit test fails on sanitizer build

Noticed, but I don't know why yet.

2023-11-24 21:19 UTC, rodiazet approved these changes

2023-11-27 10:56 UTC, gumb0 approved these changes

2023-11-27 10:59 UTC, merged